### ISSUE TITLE
could not find module ‘Data.Conduit.Zlib’

### ISSUE THREAD

**Issue by gregwebs** [snoyberg/mega-sdist#2]
cabal install mega-sdist
Resolving dependencies...
Notice: installing into a sandbox located at
/home/gweber/lib/mega-sdist/.cabal-sandbox
Configuring mega-sdist-0.2.10.4...
Building mega-sdist-0.2.10.4...
Failed to install mega-sdist-0.2.10.4
Build log ( /home/gweber/lib/mega-sdist/.cabal-sandbox/logs/mega-sdist-0.2.10.4.log ):
Configuring mega-sdist-0.2.10.4...
Building mega-sdist-0.2.10.4...
Preprocessing executable 'mega-sdist' for mega-sdist-0.2.10.4...

mega-sdist.hs:18:8:
    Could not find module ‘Data.Conduit.Zlib’
    Perhaps you meant
      Data.Conduit.List (from conduit-1.2.4)
      Data.Conduit.Lift (from conduit-1.2.4)
    Use -v to see a list of the files searched for.
cabal: Error: some packages failed to install:
mega-sdist-0.2.10.4 failed during the building phase. The exception was:
ExitFailure 1

**Comment by snoyberg** [comment]
mega-sdist is actually deprecated in favor of cabal-src

**Comment by gregwebs** [comment]
ah, I keep forgetting
